# Pytorch Tutorials
Nothing to see here, just documenting the learning I am doing for pytorch. Most of my friends say pytorch is infinitely easier than tensorflow. Let's see how easy it is gonna be. At present, I am in lockdown, and so bored I even started to clean my room. Soon that turned into a treasure hunt. From old love letters to a small bottle of sodium dipped in almost dried up kerosene, I went down the memory lane. The past is like a broken mirror. The more you explore it, the more you cut yourself and all you see is a broken reflection staring right back at you. 

So, this is me, sitting at home and breaking the chain of COVID-19. Time to learn Pytorch, because just Tensorflow alone is not gonna cut it anymore. Mostly because I don't wanna clean my room anymore.

In [0]:
# here we go
import torch

## Tensors

In [2]:
# obligatory tensor initialization
t1 = torch.tensor(4.0)
print(t1)
print(t1.dtype)
print(t1.shape)
t11 = torch.tensor(5); print(t11.dtype) # No surprises there

tensor(4.)
torch.float32
torch.Size([])
torch.int64


In [3]:
t2 = torch.tensor([1,2,3,4.0]); t2 # Vector

tensor([1., 2., 3., 4.])

In [4]:
t2.shape

torch.Size([4])

In [5]:
t3 = torch.tensor([[1,2],[3, 4.0]]); t3 # Matrix

tensor([[1., 2.],
        [3., 4.]])

In [6]:
t3.shape

torch.Size([2, 2])

Note that all the elements are converted implicitly to float32. I guess tensor is homogenous. Also, it is really eager (LOL). But right now, with tf2.0 I take eager execution for granted even when it was a pain right up the 'kernel' earlier in 1.13.

In [0]:
# This one successfully failed.
# t_fail = torch.tensor([1,2],[3]) # So, tensors should be of fixed shape. Cool.

## Tensor Operations

In [8]:
x = torch.tensor(2.0)
w = torch.tensor(3.0)
b = torch.tensor(4.0)
x,w,b

(tensor(2.), tensor(3.), tensor(4.))

In [9]:
# Obligatiory wx+b
y = w*x + b; y

tensor(10.)

## Differentiation

In [10]:
# If autograd should record operations on the returned tensor, requires_grad = True
x = torch.tensor(2.0)
w = torch.tensor(3.0, requires_grad=True) 
b = torch.tensor(4.0, requires_grad=True)
x, w, b

(tensor(2.), tensor(3., requires_grad=True), tensor(4., requires_grad=True))

In [11]:
y = w*x + b; y

tensor(10., grad_fn=<AddBackward0>)

To compute the derivatives, call .backwards() function on the result y

In [0]:
y.backward()

Derivatives of y with respect to x, w, b are stored in the x.grad,... of the tensors

In [14]:
print('dy/dx = ', x.grad) # Will return none  because we did not put requires_grad there
print('dy/dw = ', w.grad)
print('dy/db = ', b.grad)

dy/dx =  None
dy/dw =  tensor(2.)
dy/db =  tensor(1.)


## Besties with Numpy

In [15]:
import numpy as np # Ah sh!t, here we go again
x = np.array([[1,2], [3,4.]]); x

array([[1., 2.],
       [3., 4.]])

Converting numpy array to torch tensor

In [16]:
y = torch.from_numpy(x); y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [17]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

Converting torch tensor to numpy array

In [18]:
z = y.numpy(); z

array([[1., 2.],
       [3., 4.]])